language: node_js
node_js:
  - "8"

install:
  - npm ci

env:
  - JOB=test
  - JOB=build

matrix:
  include:
    - script:
        - npm test
      env: JOB=test
    - script:
        - npm run build
      env: JOB=build

cache: npm
